import { AuthProvider } from "@/providers/authProvider";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
            <h1>Bokang's App</h1>
            {children}
        </AuthProvider>
      </body>
    </html>
  );
}
